# Generated by Django 5.1.1 on 2025-12-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='featured',
            new_name='approved',
        ),
    ]
