# Generated by Django 5.1.1 on 2025-12-26 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('math_facts', 'Math Facts Practice'), ('anagram_hunt', 'Anagram Hunt')], max_length=20)),
                ('settings', models.JSONField()),
                ('final_score', models.IntegerField()),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-finished_at'],
            },
        ),
    ]
