# Generated by Django 5.1.1 on 2026-01-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game_type',
            field=models.CharField(choices=[('math_facts', 'Math Facts'), ('anagram_hunt', 'Anagram Hunt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
